//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Record = new HashSet<Record>();
        }
    
        public int ClientId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<System.DateTime> RegistartionDate { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> TagId { get; set; }

        public string ClientName { get
            {
                return $"{this.Surname} {this.Name} {this.Patronymic}";
            } }


        public virtual Gender Gender { get; set; }
        public virtual Tag Tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Record { get; set; }
    }
}
