//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string Surname { get; set; }
        public string EmployeeName { get; set; }
        public string Patronymic { get; set; }
        public string PasportSerial { get; set; }
        public string PasportNumber { get; set; }
        public string Phone { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string DivisionCode { get; set; }
        public string Birthdate { get; set; }
        public int RateId { get; set; }
        public int EmployeeCategoryId { get; set; }
    
        public virtual EmployeeCategory EmployeeCategory { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Rate Rate { get; set; }
    }
}
