//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Comment { get; set; }
        public byte[] Additionally { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
